CREATE TABLE `scooters` (
	`id` text PRIMARY KEY NOT NULL,
	`brand` text NOT NULL,
	`model` text NOT NULL,
	`image_url` text,
	`manual` text,
	`link` text,
	`weight` real NOT NULL,
	`dimension` text DEFAULT '[0,0,0]',
	`dimension_folded` text DEFAULT '[0,0,0]',
	`foldable` integer DEFAULT true,
	`battery_capacity` integer NOT NULL,
	`max_payload` integer NOT NULL,
	`climbing_angle` integer,
	`modes` text DEFAULT '[]',
	`ranges` text DEFAULT '[]',
	`speeds` text DEFAULT '[]',
	`power_max` integer NOT NULL,
	`power_nominal` integer NOT NULL,
	`wheel_drive_type` text,
	`ip_body` text,
	`ip_battery` text,
	`front_brake` text NOT NULL,
	`rear_brake` text NOT NULL,
	`tire_size` integer NOT NULL,
	`tire_type` text NOT NULL,
	`suspension` text NOT NULL,
	`price_max` integer,
	`price_min` integer,
	`description` text,
	`source` text,
	`pros` text DEFAULT '[]',
	`cons` text DEFAULT '[]',
	`warnings` text DEFAULT '[]',
	`users` text DEFAULT '[]'
);
--> statement-breakpoint
CREATE UNIQUE INDEX `scooters_source_unique` ON `scooters` (`source`);